### ISSUE TITLE
report metrics from third-party resource

### ISSUE THREAD

**Issue by philips** [kubernetes-incubator/spartakus#10]
It would be nice for people to report additional data without changing spartakus source code. I propose that we create a new third-party resource type called "SpartakusData" that can be used to report additional arbitrary data.

It would look something like this:

```
apiVersion: "k8s.io/v1"
kind: "SpartakusData"
metadata:
  name: "kube-dns"
spec:
  queries: 10040
  version: "v20"
```

This would be reported out in the payload like:

```
{
    "clusterID": "2f9c93d3-156c-47aa-8802-578ffca9b50e",
...
    "data": {
      "kube-dns": {"queries": 10040, "version": "v20"}
     }
```

Example use cases:

- Reporting Cloud Provider specific details like number of persistent disks allocated
- Allow add-ons to report usage data e.g. how many DNS queries from kube-dns
- Track install specific metrics like other component versions

cc @squat @sym3tri
